language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"
install:
    - pip install coverage nose
    - python setup.py install
script:
    - nosetests -v
      --with-doctest --doctest-extension=py --doctest-extension=rst
      --with-coverage --cover-package=skiplistcollections
