language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"
install:
    - pip install coverage flake8 nose
    - python setup.py install
script:
    - flake8 --max-line-length=110 *.py
    - nosetests -v
      --with-doctest --doctest-extension=py --doctest-extension=rst
      --with-coverage --cover-package=skiplistcollections
